### ISSUE TITLE
torch.mean(input, (2, 3))

### ISSUE THREAD

**Issue by jiezishu737** [pxq0312/ASD-crowd-counting#2]
请问一下，这个torch.mean为什么有两个参数。应该只有一个input参数吧，另一个参数是啥意思？我用的pytorch0.4，这个是因为pytorch版本的问题吗？

谢谢

**Comment by pxq0312** [comment]
第二个参数是求平均的维度，也就是对NxCxHxW的H和W维求平均，得到NxC的输出。在pytorch 1.0之后的版本中才可以在维度处传入元组，0.4版本中可以调用两次mean，依次对第3维和第2维求平均。

**Comment by jiezishu737** [comment]
谢谢
